artikelpage/urls.py
from django.urls import path
from .views import HomeView, ArticleDetailView, AddPostView, UpdatePostView, DeletePost

app_name = 'artikelpage'

urlpatterns = [
    path('', HomeView.as_view(), name='artikel'),
    path('artdetail/<int:pk>', ArticleDetailView.as_view(), name='article-detail'),
    path('addarticle/', AddPostView.as_view(), name='add_article'),
    path('artdetail/edit/<int:pk>', UpdatePostView.as_view(), name='update'),
    path('artdetail/delete/<int:pk>', DeletePost.as_view(), name='delete'),
]

feedback/urls.py
from django.urls import path
from . import views

app_name = 'feedback'

urlpatterns = [
    path('', views.feedback, name='feedback'),
    path('feedback', views.feedback, name="feedback"),
]

susun_deadline/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('artikel/', include('artikelpage.urls')),
    path('feedback/', include('feedback.urls')),
    path('help-page/', include('help_page.urls')),
]

artikelpage/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.shortcuts import redirect
from datetime import datetime,date
from ckeditor.fields import RichTextField

# Create your models here.

# class Author(models.Model):
#     name = models.CharField(max_length=255)
#     email = models.CharField(max_length=255)

#     def __str__(self):
#         return self.name

class Post(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    body = RichTextField(blank=True,null=True)
    article_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title + '  |  ' +str(self.author)

    def get_absolute_url(self):
        # return reverse('artikelpage:article-detail', args=(str(self.id)))
        return reverse('artikelpage:artikel')

artikelpage/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','author','body')
        widgets = {
            'title' : forms.TextInput(attrs={'class': 'form-control'}),
            'author' : forms.Select(attrs={'class': 'form-control'}),
            'body' : forms.Textarea(attrs={'class': 'form-control'}),
        }

class EditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','body')
        widgets = {
            'title' : forms.TextInput(attrs={'class': 'form-control'}),
            'body' : forms.Textarea(attrs={'class': 'form-control'}),
        }

artikelpage/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post
from .forms import PostForm, EditForm
from django.urls import reverse_lazy

# Create your views here.
# def artikel(request):
#     return render(request,'articlepage.html')

class HomeView(ListView):
    model = Post
    template_name = 'articlepage.html'
    ordering = ['article_date']

class ArticleDetailView(DetailView):
    model = Post
    template_name = 'articledetail.html'

class AddPostView(CreateView):
    model = Post
    template_name = 'addarticle.html'
    form_class = PostForm
    # fields = '__all__'

class UpdatePostView(UpdateView):
    model = Post
    template_name = 'updatearticle.html'
    form_class = EditForm
    # fields = ['title', 'body']

class DeletePost(DeleteView):
    model = Post
    template_name = 'deletearticle.html'
    success_url = reverse_lazy('artikelpage:artikel')

artikelpage/templates/addarticle.html
{% extends 'base1.html' %}
{% load static %}
{% block content %}
        <h1>Add Article </h1>
        <div class="form-group">
        <form method="POST">
            {% csrf_token %}
            {{ form.media}}
            {{ form.as_p}}
            <button class="btn btn-primary"> Post </button>
        </div>
{% endblock %} 

artikelpage/templates/articledetail.html
{% extends 'base1.html' %}
{% load static %}
{% block content %}
        <h1>{{ post.title }} </h1>
        <small>By: {{post.author}}   -   {{post.article_date}} - <small><a href="{% url 'artikelpage:update' post.pk %}">  (Edit)</a></small> <small><a href="{% url 'artikelpage:delete' post.pk %}">  (Delete)</a></small></small><br/>
        <hr>
        <br/>
        {{ post.body |slice:":200"|safe}}
        <br/><br/>
        <a href="{% url 'artikelpage:artikel'%}"class="btn btn-secondary">Back</a>
{% endblock %} 

artikelpage/templates/articlepage.html
{% extends 'base1.html' %}
{% load static %}
{%block content%}

        <h1>Article</h1>
        <ul>
            {% for post in object_list %}
                <li><a href="{% url 'artikelpage:article-detail' post.pk %}" >{{post.title }}</a> - {{post.author}} - {{post.article_date}} - <small><a href="{% url 'artikelpage:update' post.pk %}">  (Edit)</a></small> <small><a href="{% url 'artikelpage:delete' post.pk %}">  (Delete)</a></small>
                </br> {{ post.body |slice:":200"|safe}}
                </li>
            {% endfor %}
        </ul>
{%endblock%}

artikelpage/templates/base1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Susun Jadwal</title>
  
  <!-- CSS only -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'base.css' %}">

  <!-- JS, Popper.js, and jQuery -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</head>

<body>
  <div class="navigation">
    <div class="menu-bar">
      <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="#">SusunDeadline</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ml-auto">
            <a class="nav-link active" href="/susundeadline">Buat Jadwal</a>
            <a class="nav-link" href="/daftarjadwal">Daftar Jadwal</a>
            <a class="nav-link" href="/artikel">Article</a>
            <a class="nav-link" href="{% url 'artikelpage:add_article'%}">Add Article</a>
            <a class="nav-link" href="/quotes">Quotes</a>
          </div>
        </div>
      </nav>
    </div>
    
  </div>
  <br/>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
</body>

</html>

artikelpage/templates/deletearticle.html
{% extends 'base1.html' %}
{% load static %}
{% block content %}
        <h1>Delete Article </h1>
        <br/><br/>
        <h3>Delete: {{ post.title }}</h3>
        <br/>
        <div class="form-group">
        <form method="POST">
            {% csrf_token %}
            <button class="btn btn-warning"> Delete Post </button>
        </div>
{% endblock %} 

artikelpage/templates/updatearticle.html
{% extends 'base1.html' %}
{% load static %}
{% block content %}
        <h1>Update </h1>
        <div class="form-group">
        <form method="POST">
            {% csrf_token %}
            {{ form.media}}
            {{ form.as_p}}
            <button class="btn btn-primary"> Update </button>
        </div>
{% endblock %} 