artikelpage/urls.py
from django.urls import path
from .views import HomeView, ArticleDetailView, AddPostView, UpdatePostView, DeletePost

app_name = 'artikelpage'

urlpatterns = [
    path('', HomeView.as_view(), name='artikel'),
    path('artdetail/<int:pk>', ArticleDetailView.as_view(), name='article-detail'),
    path('addarticle/', AddPostView.as_view(), name='add_article'),
    path('artdetail/edit/<int:pk>', UpdatePostView.as_view(), name='update'),
    path('artdetail/delete/<int:pk>', DeletePost.as_view(), name='delete'),
]

feedback/urls.py
from django.urls import path
from . import views

app_name = 'feedback'

urlpatterns = [
    path('', views.feedback, name='feedback'),
    path('feedback', views.feedback, name="feedback"),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('susundeadline', views.create, name='create'),
    path('daftarjadwal', views.index),
    path('quotes', views.cetakquote, name="cetakquote"),
    path('formquotes', views.quotes, name="quotes"),
    path('update/<int:update_id>', views.update, name='update'),
    path('delete/<int:delete_id>', views.delete, name='delete'),
    path('quotes', views.cetakquote, name="cetakquote"),
]

susun_deadline/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('artikel/', include('artikelpage.urls')),
    path('feedback/', include('feedback.urls')),
    path('help-page/', include('help_page.urls')),
]

homepage/models.py
from django.db import models
from django.core.exceptions import ValidationError
# Create your models here.
# memvalidasi di model krn yg ingin di validasi model 

def validate_author(value):
    judul_input = value
    if judul_input == "Einstein":
        message = "maaf" + judul_input + "tidak bisa diposting"
        raise ValidationError(message)

class PostModel(models.Model):
    Mata_Kuliah = models.CharField(max_length=100)
    Nama_Tugas = models.TextField(
        max_length=300,
        validators= [validate_author]
        )
    Deadline = models.CharField(max_length=100)

    published = models.DateTimeField(auto_now_add=True)
    
def __str__(self):
    return "{}.{}".format(self.id, self.judul)

class formquote(models.Model):
    Quote = models.CharField(max_length=500)
    nama = models.CharField(max_length=100)

    def __str__(self):
        return self.Quote


homepage/forms.py
from django import forms

#import model dari models.py
from .models import PostModel, formquote

class PostForm(forms.ModelForm):
    class Meta:
        model = PostModel
        fields = [
            'Mata_Kuliah',
            'Nama_Tugas',
            'Deadline',           
        ]
        widgets = {
            'Mata_Kuliah': forms.TextInput(  
                attrs={
                    'class' : 'form-control', 
                    'placeholder' : 'Tuliskan nama Mata kuliah',
                }
            ),
            'Nama_Tugas': forms.TextInput(  
                attrs={
                    'class' : 'form-control',
                    'placeholder' : 'Tuliskan nama tugas anda',
                }
            ),      
            'Deadline': forms.TextInput(  
                attrs={
                    'class' : 'form-control', 
                    'placeholder' : 'Tuliskan tenggat waktu dari tugas anda',
                }
            ),
        }
# pada bagian ini form susun deadline memiliki tiga data yang harus disubmit oleh pengguna

#lisa:

class QuoteForm(forms.ModelForm):
    class Meta:
        model = formquote
        fields = '__all__'

        widgets = {
            'Quote' : forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Tuliskan Quote Motivasi'}),
            'nama' : forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Tuliskan Nama'}),
        }

    error_messages = { 'required' : 'Please Type' }

    input_attrs = {
        'type' : 'text',
    }

homepage/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
# Create your views here.
from .forms import PostForm, QuoteForm
from .models import PostModel, formquote

def homepage(request):
    return render(request, 'homepage.html')

def index(request):
    posts = PostModel.objects.all()
    context = {
        'heading' : 'Post',
        'contents': 'List Post',
        'posts' : posts,
    }
    return render(request, 'daftarjadwal.html', context)

def create(request):
    post_form = PostForm(request.POST or None)
    if request.method == 'POST':
        #cara ambil data dari input user ke database dg validasi
        if post_form.is_valid():
            post_form.save()
        return HttpResponseRedirect("/daftarjadwal")

    
    context = {
        'pageTitle' : 'Create Form',
        'post_form' : post_form,
    }
    return render(request, 'susundeadline.html', context)

def update(request, update_id):
    akun_update = PostModel.objects.get(id=update_id)
    data = {
        'Mata_Kuliah' : akun_update.Mata_Kuliah,
        'Nama_Tugas' : akun_update.Nama_Tugas,
        'Deadline' : akun_update.Deadline,
    }
    post_form = PostForm(request.POST or None, initial=data, instance=akun_update)

    if request.method == 'POST':
        #cara ambil data dari input user ke database dg validasi
        if post_form.is_valid():
            post_form.save()
        return HttpResponseRedirect("/daftarjadwal")

    
    context = {
        'pageTitle' : 'Update Form',
        'post_form' : post_form,
    }
    return render(request, 'story5/susundeadline.html', context)

def delete(request, delete_id):
    PostModel.objects.filter(id=delete_id).delete()
    return HttpResponseRedirect("/daftarjadwal")

def quotes(request):
    if(request.method=='POST'):
        qts = QuoteForm(request.POST or None)
        if qts.is_valid():
            qts.save()
            return HttpResponseRedirect("/quotes")
    response = {'form_quote' : QuoteForm}
    return render(request, 'FormQuotes.html', response)

def cetakquote(request):
    infoquote = formquote.objects.all()
    print(infoquote)
    response = {'quotesnya' : infoquote}
    return render(request, 'quotes.html', response)





    

homepage/templates/FormQuotes.html
{% include 'base.html' %}
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>Susun Deadline</title>
</head>
<body>
    <div class="jumbotron">
        <div class="form-group mx-auto" style="text-align: center; width: 30%;">
            <form action="" method="POST">
                {% csrf_token %}
                {{form_quote.Quote}}<br>
                {{form_quote.nama}}<br>
                <button class="btn btn-primary" type="Submit">Submit</button>
            </form>
        </div>
    </div>
</body>

homepage/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Susun Jadwal</title>
  
  <!-- CSS only -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'base.css' %}">
  
  <!-- JS, Popper.js, and jQuery -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</head>

<body>
  <div class="navigation">
    <div class="menu-bar">
      <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="/">SusunDeadline</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ml-auto">
            <a class="nav-link active" href="/susundeadline">Buat Jadwal</a>
            <a class="nav-link" href="/daftarjadwal">Daftar Jadwal</a>
            <a class="nav-link" href="/artikel">Artikel</a>
            <a class="nav-link" href="{% url 'artikelpage:add_article'%}">Add Article</a>
            <a class="nav-link" href="/quotes">Quotes</a>
            <a class="nav-link" href="/feedback">Feedback</a>
            <a class="nav-link" href="/help-page">FAQ & Contacts</a>
          </div>
        </div>
      </nav>
    </div>
    
  </div>
</body>

</html>

homepage/templates/daftarjadwal.html
{% include 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Susun Deadline</title>
    <style>
        #jumbo-index .jumbotron{
            background-size: cover;
            background-position: center;
            height: 650px;
            width: 100%;
        }
    </style>
</head>
<body>
    <section id="jumbo-index">
        <div class="jumbotron jumbotron-fluid">
            <div class="container"> 
                <div class="container-fluid" style="margin-top: 30px;">
                    <div class="container text-white" style="height: 640px;">
                        <h1>Ringkasan Tugas</h1>
                        <table class="table">
                            <thead class="table  text-blue text-center">
                                <th scope="col">Mata Kuliah</th>
                                <th scope="col">Nama Tugas</th>
                                <th scope="col">Deadline</th>
                            </thead>
                            <tbody>
                                {% for a in posts %}
                                <tr class="table text-blue text-center">
                                    <td> {{a.Mata_Kuliah}} </td>
                                    <td> {{a.Nama_Tugas}} </td>
                                    <td> {{a.Deadline}} </td>
                                    <td><a class="btn btn-danger" href="{% url 'homepage:delete' a.id %}">Delete</a></td>
                                    <td><a class="btn btn-warning" href="{% url 'homepage:update' a.id %}">Update</a></td>
                                </tr> 
                                {% endfor %}
                            </tbody>
                        </table>
                        <a class="btn btn-primary" href="/susundeadline">Tambahkan Tugas Lain</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
</html>

homepage/templates/homepage.html
{% include 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Susun Deadline</title>
</head>
<body>
    <div class="jumbotron">
        <p class="lead" style="font-size: 40px;">Welcome to Susun Deadline!</p>
        <h1>[tu.gas]</h1>
        <h3>Pekerjaan yang menjadi tanggung jawab seseorang</h3>
        <hr class="my-2">
        <p>Ayo susun deadlinemu sekarang!</p>
        <p class="lead">
          <a class="btn btn-primary btn-lg" href="/susundeadline" role="button">Mulai menyusun deadline</a>
        </p>
      </div>      
</body>
</html>

homepage/templates/login.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>Susun Deadline</title>
</head>
<body>
    <div class="card text-center">
        <div class="card-header">
          <h1>Susun Deadline</h1>
        </div>
        <div class="card-body">
            <img src="{% static 'IconDeadline.png' %}" width="100" height="100">
            <h5 class="card-title">Log in to SusunDeadline</h5>
            <div class="card-text">
              <form method = "POST" action="">
                {% csrf_token %}
                {{form_user.Nama}}
                {{form_user.NPM}}
                <br>
                <button class="btn btn-primary" type="Submit">Log in</button>
              </form>
          </div>
        </div>
    </div>
</body>
</html>

homepage/templates/quotes.html
{% include 'base.html' %}
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>Susun Deadline</title>
</head>
<body>
    <div class="jumbotron">
        <h2 style="text-align: center;">Quotes Motivasi</h2><br>
        {% for form_quote in quotesnya %}
        <div class="card text-center" style="width: 20%; margin-left: auto; margin-right: auto;">
            <div class="card-body">
                <h5 class="card-title">{{form_quote.Quote}}</h5>
            </div>
            <div class="card-footer text-muted">
                by {{form_quote.nama}}
            </div>
        </div>
        <br>
        {% endfor %}
        <a class="btn btn-primary btn-lg" href="/formquotes" role="button">Tulis Quotes</a>
    </div>
</body>
</html>

homepage/templates/susundeadline.html
{% include 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Susun Deadline</title>
</head>
<body>
    <section id="jumbo-index">
        <div class="jumbotron jumbotron-fluid">
            <div class="container">
                <section name="form">
                    <div class="container-fluid">
                        <div class="container text-blue" style="height: 670px;">
                            <h1>Atur Jadwal</h1>
                            <form method = "POST" action="">
                                {% csrf_token %}
                                {% for a in post_form %}
                                <div class="form-group">
                                    {{a.label}}
                                    {{a}}
                                </div>
                                {% endfor %}
                                <button class="btn btn-primary" type="Submit">Submit</button>
                            </form>
                        </div>
                    </div> 
            
                </section>
            </div>
        </div>
    </section>   
</body>
</html>

<style>
    #jumbo-index .jumbotron{
        background-size: cover;
        background-position: center;
        height: 1100px;
        width: 100%;
    }
    .btn {
        padding: 7px 30px;
        margin-right: 30px;
        outline: none;
        border: 1px solid #fb7381;
        border-radius: 20px;
        cursor: pointer;
        color: #fb7381;
        background: transparent;
    }
    #jumbo-index .jumbotron{
        background-size: cover;
        background-position: center;
        height: 650px;
        width: 100%;
    }
</style>